name: Concurrency 2
run-name: Concurrency 2 (${{ inputs.environment }})
on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Environment"
                type: environment
                required: true
concurrency:
    group: ${{ github.workflow }}-${{ github.event.inputs.environment }} # add dynamic concurrency groups
    cancel-in-progress: true # it will cancel run in progress as well, (default is it cancels the recent ones, leaves the oldest one, waits for it to finish, then runs the latest one.)
jobs:
    sleep:
        runs-on: ubuntu-latest
        steps:
            - run: sleep 30