name: Docker
on: [workflow_dispatch]

jobs:
    docker-job:
        runs-on: ubuntu-latest
        container: 
            image: node:23-alpine3.20
            # credentials if using a private repository
            # credentials:
            #     username: "username"
            #     password: "password"
            env:
                API_URL: some-url.com
            ports:
                - 80
            # volumes:
            #     - vol_name:/path/in/container
            #     - /path/to/container
            #     - /path/in/host:/path/in/container
            # options: --cpus 1
        steps:
            - name: Log Node & OS version
              run: |
                node -v
                cat /etc/os-release
            - name: log env
              run: echo $API_URL
            - name: Create a file
              run: echo 'Some text' > file.txt
            - name: Log node version
              uses: docker://node:18.16-alpine3.17
              with:
                entrypoint: /usr/local/bin/node
                args: -p 2
            - name: Log node version
              uses: docker://node:18.16-alpine3.17
              with:
                args: -v
            - name: Show file contents
              uses: docker://node:18.16-alpine3.17
              with:
                cmd: cat file.txt