name: Repository events
on: 
    push:
        branches:
            - main
            - "feature/*"
            - "!feature/featA"
        # branches-ignore:
        #     - develop
        tags:
            - v1.*
            - "!v1.1.1"
        paths:
            - "**.py"
            - "!app.js"
    pull_request:
        types: [opened, assigned, reopened, synchronize]
        branches:
            - main
        paths:
            "**.py"
    issues:
        types: [opened]

jobs:
    checkout-test:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo $GITHUB_SHA
                echo $GITHUB_REF
            - uses: actions/checkout@v4