name: Reusable Yaml
on:
    workflow_call:
        inputs:
            name:
                description: 'Input description'
                type: string
                default: 'Hello'
                required: false
        secrets:
            access-token:
                description: 'Secret Description'
                required: true

jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: ls -a
    log-context-and-inputs:
        runs-on: ubuntu-latest
        steps:
            - name: Display github context
              run: echo '${{ toJson(github) }}'
            - name: Display name input
              run: echo '${{ github.event.inputs.name }}'
            - name: Display access token secret
              run: echo '${{ secrets.access-token }}'
              