name: Calling Reusable Workflows
on:
    workflow_dispatch:
        inputs:
            name:
                description: "Input Description"
                type: string
                default: "Hello"
                required: false

jobs:
    calling-a-reusable-workflow:
        uses: smandalsid/GithubActions-WorkFlows/.github/workflows/reusable.yaml@main
        with:
            name: ${{ github.event.inputs.name }}
        secrets:
            access-token: ${{ secrets.ACCESS_TOKEN }}
    calling-a-reusable-wf-in-the-same-repo:
        uses: ./.github/workflows/reusable-workflow-2.yaml
    using-reusable-wf-output:
        runs-on: ubuntu-latest
        needs: calling-a-reusable-wf-in-the-same-repo
        steps:
            - run: echo ${{ needs.calling-a-reusable-wf-in-the-same-repo.outputs.date }}