name: Workflow run
on:
    workflow_run:
        workflows: [Repository events]
        types: [completed]
        branches:
            - main
jobs:
    echo-string:
        runs-on: ubuntu-latest
        steps:
            - run: echo "I was triggered because repository events from events.yaml file ran"